# Copyright (c) 2024 Humanitarian OpenStreetMap Team
#
# This file is part of FMTM.
#
#     FMTM is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     FMTM is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with FMTM.  If not, see <https:#www.gnu.org/licenses/>.
#

# Test backend & frontend
[no-cd]
all: backend frontend

# Test backend with pytest
[no-cd]
backend:
  docker compose run --rm api pytest

# Test frontend with Playwright
[no-cd]
frontend:
  API_URL_OVERRIDE="http://api:8000" docker compose build ui
  docker compose run --rm --service-ports ui-test

# Check coverage for backend tests
[no-cd]
coverage:
  docker compose run --rm --entrypoint='sh -c' api \
    'coverage run -m pytest && coverage report -m'
