# Copyright (c) Humanitarian OpenStreetMap Team
#
# This file is part of Field-TM.
#
#     Field-TM is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     Field-TM is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with Field-TM.  If not, see <https:#www.gnu.org/licenses/>.
#

# Stop Field-TM
[no-cd]
default:
  docker compose down

# Stop Field-TM & JOSM
[no-cd]
josm:
  docker compose \
    -f compose.yaml \
    -f contrib/josm/compose.yaml \
    down
  
# Stop Field-TM & tunnels
[no-cd]
tunnel:
  docker compose \
    -f compose.yaml \
    -f contrib/tunnel/compose.yaml \
    down

