
import {
    LocationOn,
    AutoAwesome,
    Search as SearchIcon,
    Close as CloseIcon,
    Person as PersonIcon,
    Login as LoginIcon,
    Menu as MenuIcon,
    KeyboardArrowDown as KeyboardArrowDownIcon,
    DarkMode as DarkModeIcon,
    LightMode as LightModeIcon,
    Link as LinkIcon,
    Rectangle as RectangleIcon,
    AccessTimeFilled as AccessTimeFilledIcon,
    Lock as LockIcon,
    Fullscreen as FullscreenIcon,
    MyLocation as MyLocationIcon,
    GridView as GridViewIcon,
    Add as AddIcon,
    FormatAlignCenter as FormatAlignCenterIcon,
    Remove as RemoveIcon,
    KeyboardDoubleArrowUp as KeyboardDoubleArrowUpIcon,
    KeyboardDoubleArrowDown as KeyboardDoubleArrowDownIcon,
    Verified as VerifiedIcon,
    LockOpen as LockOpenIcon,
    Description as DescriptionIcon,
    FileDownload as FileDownloadIcon,
    Share as ShareIcon,
    ExitToApp as ExitToAppIcon
} from '@mui/icons-material';

import { styled, alpha } from '@mui/material/styles';
export default {
    ExitToAppIcon,
    ShareIcon,
    VerifiedIcon,
    LockOpenIcon,
    DescriptionIcon,
    FileDownloadIcon,
    LocationOn,
    AutoAwesome,
    SearchIcon,
    styled,
    alpha,
    CloseIcon,
    PersonIcon,
    LoginIcon,
    KeyboardArrowDownIcon,
    DarkModeIcon,
    LightModeIcon,
    MenuIcon,
    LinkIcon,
    RectangleIcon,
    AccessTimeFilledIcon,
    LockIcon,
    FullscreenIcon,
    MyLocationIcon,
    GridViewIcon,
    AddIcon,
    FormatAlignCenterIcon,
    RemoveIcon,
    KeyboardDoubleArrowUpIcon,
    KeyboardDoubleArrowDownIcon
}