"frontend":
  - "src/frontend/**/*"
"backend":
  - "src/backend/**/*"
"devops":
  - ".github/**/*"
  - "nginx/**/*"
  - "scripts/**/*"
  - "docker-*.yml"
  - "**/Dockerfile"
  - "**/*.dockerfile"
  - "**/*entrypoint.sh"
"migration":
  - "src/backend/migrations/**/*"
"documentation":
  - "docs/**/*"
  - "images/**/*"
  - "mkdocs.yml"
  - "README.md"
  - "INSTALL.md"
"ODK":
  - "odkcentral/**/*"
"contrib":
  - "contrib/**/*"
