# Copyright (c) Humanitarian OpenStreetMap Team
# This file is part of Field-TM.
#
#     Field-TM is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     Field-TM is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with Field-TM.  If not, see <https:#www.gnu.org/licenses/>.
#

volumes:
  fmtm_monitoring_data:
    name: fmtm-monitoring-data-local

networks:
  fmtm-net:
    name: fmtm-${GIT_BRANCH:-local}

services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    environment:
      ZO_ROOT_USER_EMAIL: ${OPENOBSERVE_USER}
      ZO_ROOT_USER_PASSWORD: ${OPENOBSERVE_PASSWORD}
      # Keep data 90 days
      ZO_COMPACT_DATA_RETENTION_DAYS: ${OPENOBSERVE_RETENTION_DAYS}
      # S3 config
      # ZO_LOCAL_MODE_STORAGE: s3
      # ZO_S3_SERVER_URL: ${S3_xx}
      # ZO_S3_REGION_NAME: us-west-1
      # ZO_S3_ACCESS_KEY: ${S3_xx}
      # ZO_S3_SECRET_KEY: ${S3_xx}
      # ZO_S3_BUCKET_NAME: ${S3_xx}
      # ZO_S3_PROVIDER: s3
    ports:
      - "5080:5080"
    volumes:
      - fmtm_monitoring_data:/data
    networks:
      - fmtm-net
    restart: unless-stopped
    # TODO add healthcheck
