export enum task_split_type {
  divide_on_square = 'DIVIDE_ON_SQUARE',
  choose_area_as_task = 'CHOOSE_AREA_AS_TASK',
  task_splitting_algorithm = 'TASK_SPLITTING_ALGORITHM',
}

export enum task_status {
  RELEASED_FOR_MAPPING = 'RELEASED_FOR_MAPPING',
  LOCKED_FOR_MAPPING = 'LOCKED_FOR_MAPPING',
  MARKED_MAPPED = 'MARKED_MAPPED',
  LOCKED_FOR_VALIDATION = 'LOCKED_FOR_VALIDATION',
  VALIDATED = 'VALIDATED',
  MARKED_INVALID = 'MARKED_INVALID',
  MARKED_BAD = 'MARKED_BAD',
  SPLIT_NEEDED = 'SPLIT_NEEDED',
  RECREATED = 'RECREATED',
  COMMENT = 'COMMENT',
}

export enum user_roles {
  READ_ONLY = 'READ_ONLY',
  MAPPER = 'MAPPER',
  ADMIN = 'ADMIN',
}
