# Copyright (c) Humanitarian OpenStreetMap Team
#
# This file is part of Field-TM.
#
#     Field-TM is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     Field-TM is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with Field-TM.  If not, see <https:#www.gnu.org/licenses/>.
#

# Rename docker volume
[no-cd]
rename-volume oldname newname:
  #!/usr/bin/env sh

  docker volume create {{newname}}

  docker run --rm \
    -i \
    -v {{oldname}}:/from \
    -v {{newname}}:/to \
    alpine ash -c "cd /from && cp -a . /to"

  echo ""
  echo "Renamed {{oldname}} to {{newname}}"
  echo "You can now safely delete {{oldname}}"
