"""Initial migration

Revision ID: d78228ef4302
Revises: 
Create Date: 2022-10-08 15:09:11.234184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd78228ef4302'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('feature_id', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('status', sa.Enum('available', 'unavailable', 'ready_for_validation', name='taskstatus'), nullable=False))
    op.drop_column('tasks', 'in_progress')
    op.drop_column('tasks', 'task_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('in_progress', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'status')
    op.drop_column('tasks', 'feature_id')
    # ### end Alembic commands ###
