FROM docker.io/node:18
ARG APP_NAME
ARG URL_SCHEME
ARG API_URL
ENV API_URL=${URL_SCHEME}://${API_URL}
ARG FRONTEND_MAIN_URL
ENV FRONTEND_MAIN_URL=${URL_SCHEME}://${FRONTEND_MAIN_URL}
ARG FRONTEND_MAP_URL
ENV FRONTEND_MAP_URL=${URL_SCHEME}://${FRONTEND_MAP_URL}
WORKDIR /app
COPY ./${APP_NAME}/package*.json ./
RUN npm install
ENV NODE_ENV development
ENTRYPOINT ["npm", "run", "start:live"]
