export const languages = [
	{ code: 'af', name: 'Afrikaans', flag: '🇿🇦' },
	{ code: 'sq', name: 'Shqip', flag: '🇦🇱' },
	{ code: 'am', name: 'አማርኛ', flag: '🇪🇹' },
	{ code: 'en', name: 'English', flag: '🇬🇧' },
	{ code: 'ar', name: 'العربية', flag: '🇸🇦' },
	{ code: 'hy', name: 'Հայերեն', flag: '🇦🇲' },
	{ code: 'my', name: 'ဗမာ', flag: '🇲🇲' },
	{ code: 'eu', name: 'Euskara', flag: '🇪🇸' },
	{ code: 'bn', name: 'বাংলা', flag: '🇧🇩' },
	{ code: 'bg', name: 'Български', flag: '🇧🇬' },
	{ code: 'be', name: 'Беларуская', flag: '🇧🇾' },
	{ code: 'hr', name: 'Hrvatski', flag: '🇭🇷' },
	{ code: 'da', name: 'Dansk', flag: '🇩🇰' },
	{ code: 'et', name: 'Eesti', flag: '🇪🇪' },
	{ code: 'tl', name: 'Filipino', flag: '🇵🇭' },
	{ code: 'fi', name: 'Suomi', flag: '🇫🇮' },
	{ code: 'fr', name: 'Français (France)', flag: '🇫🇷' },
	{ code: 'gl', name: 'Galego', flag: '🇪🇸' },
	{ code: 'ka', name: 'ქართული', flag: '🇬🇪' },
	{ code: 'gu', name: 'ગુજરાતી', flag: '🇮🇳' },
	{ code: 'he', name: 'עברית', flag: '🇮🇱' },
	{ code: 'hi', name: 'हिन्दी', flag: '🇮🇳' },
	{ code: 'id', name: 'Indonesia', flag: '🇮🇩' },
	{ code: 'is', name: 'Íslenska', flag: '🇮🇸' },
	{ code: 'it', name: 'Italiano', flag: '🇮🇹' },
	{ code: 'ja', name: '日本語', flag: '🇯🇵' },
	{ code: 'kn', name: 'ಕನ್ನಡ', flag: '🇮🇳' },
	{ code: 'ca', name: 'Català', flag: '🇪🇸' },
	{ code: 'kk', name: 'Қазақ тілі', flag: '🇰🇿' },
	{ code: 'km', name: 'ខ្មែរ', flag: '🇰🇭' },
	{ code: 'ko', name: '한국어', flag: '🇰🇷' },
	{ code: 'ky', name: 'Кыргызча', flag: '🇰🇬' },
	{ code: 'lo', name: 'ລາວ', flag: '🇱🇦' },
	{ code: 'lt', name: 'Lietuvių', flag: '🇱🇹' },
	{ code: 'lv', name: 'Latviešu', flag: '🇱🇻' },
	{ code: 'mk', name: 'Македонски', flag: '🇲🇰' },
	{ code: 'ml', name: 'മലയാളം', flag: '🇮🇳' },
	{ code: 'ms-MY', name: 'Bahasa Melayu (Malaysia)', flag: '🇲🇾' },
	{ code: 'ms', name: 'Bahasa Melayu', flag: '🇲🇾' },
	{ code: 'mr', name: 'मराठी', flag: '🇮🇳' },
	{ code: 'hu', name: 'Magyar', flag: '🇭🇺' },
	{ code: 'mn', name: 'Монгол', flag: '🇲🇳' },
	{ code: 'ne', name: 'नेपाली', flag: '🇳🇵' },
	{ code: 'nl', name: 'Nederlands', flag: '🇳🇱' },
	{ code: 'no', name: 'Norsk', flag: '🇳🇴' },
	{ code: 'de', name: 'Deutsch', flag: '🇩🇪' },
	{ code: 'pa', name: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
	{ code: 'fa', name: 'فارسی', flag: '🇮🇷' },
	{ code: 'pl', name: 'Polski', flag: '🇵🇱' },
	{ code: 'pt-BR', name: 'Português (Brasil)', flag: '🇧🇷' },
	{ code: 'pt', name: 'Português', flag: '🇵🇹' },
	{ code: 'ro', name: 'Română', flag: '🇷🇴' },
	{ code: 'ru', name: 'Русский', flag: '🇷🇺' },
	{ code: 'rm', name: 'Rumantsch', flag: '🇨🇭' },
	{ code: 'si', name: 'සිංහල', flag: '🇱🇰' },
	{ code: 'sk', name: 'Slovenčina', flag: '🇸🇰' },
	{ code: 'sl', name: 'Slovenščina', flag: '🇸🇮' },
	{ code: 'sr', name: 'Српски', flag: '🇷🇸' },
	{ code: 'sw', name: 'Kiswahili', flag: '🇹🇿' },
	{ code: 'ta', name: 'தமிழ்', flag: '🇮🇳' },
	{ code: 'te', name: 'తెలుగు', flag: '🇮🇳' },
	{ code: 'th', name: 'ไทย', flag: '🇹🇭' },
	{ code: 'tr', name: 'Türkçe', flag: '🇹🇷' },
	{ code: 'uk', name: 'Українська', flag: '🇺🇦' },
	{ code: 'ur', name: 'اردو', flag: '🇵🇰' },
	{ code: 'vi', name: 'Tiếng Việt', flag: '🇻🇳' },
	{ code: 'zu', name: 'Zulu', flag: '🇿🇦' },
	{ code: 'az', name: 'Azərbaycan dili', flag: '🇦🇿' },
	{ code: 'cs', name: 'Čeština', flag: '🇨🇿' },
	{ code: 'zh-HK', name: '中文（香港）', flag: '🇭🇰' },
	{ code: 'zh-TW', name: '中文（繁體）', flag: '🇹🇼' },
	{ code: 'zh', name: '中文（简体）', flag: '🇨🇳' },
	{ code: 'el', name: 'Ελληνικά', flag: '🇬🇷' },
	{ code: 'es-419', name: 'Español (Latinoamérica)', flag: '🌎' },
	{ code: 'es', name: 'Español', flag: '🇪🇸' },
	{ code: 'sv', name: 'Svenska', flag: '🇸🇪' },
];
