import {
  LocationOn,
  AutoAwesome,
  Search as SearchIcon,
  Close as CloseIcon,
  Person as PersonIcon,
  Login as LoginIcon,
  Menu as MenuIcon,
  KeyboardArrowDown as KeyboardArrowDownIcon,
  DarkMode as DarkModeIcon,
  LightMode as LightModeIcon,
  Link as LinkIcon,
  Rectangle as RectangleIcon,
  AccessTimeFilled as AccessTimeFilledIcon,
  Lock as LockIcon,
  Fullscreen as FullscreenIcon,
  GridView as GridViewIcon,
  Add as AddIcon,
  FormatAlignCenter as FormatAlignCenterIcon,
  Remove as RemoveIcon,
  KeyboardDoubleArrowUp as KeyboardDoubleArrowUpIcon,
  KeyboardDoubleArrowDown as KeyboardDoubleArrowDownIcon,
  Verified as VerifiedIcon,
  LockOpen as LockOpenIcon,
  Description as DescriptionIcon,
  FileDownload as FileDownloadIcon,
  Share as ShareIcon,
  ExitToApp as ExitToAppIcon,
  SettingsSuggest as SettingsSuggestIcon,
  ArrowBack as ArrowBackIcon,
  Task as TaskIcon,
  UploadFile as SubmissionIcon,
  PlaylistAddCheck as FeatureIcon,
  Bolt as BoltIcon,
  Window as WindowIcon,
  FormatListBulleted as ListViewIcon,
  FilterAlt as FilterAltIcon,
  ArrowLeft as ArrowLeftIcon,
  ArrowRight as ArrowRightIcon,
  Done as DoneIcon,
  Replay as ReplayIcon,
  Settings as SettingsIcon,
  DriveFolderUpload as DriveFolderUploadIcon,
  KeyboardArrowUp as KeyboardArrowUpIcon,
  Info as InfoIcon,
  MoreVert as MoreVertIcon,
  LocationOn as LocationOnIcon,
  CropFree as CropFreeIcon,
  LegendToggle as LegendToggleIcon,
  Delete as DeleteIcon,
  ListAlt as ListAltIcon,
  Map as MapIcon,
  FilterAltOutlined as FilterAltOutlinedIcon,
  ArrowForwardIos as ArrowForwardIosIcon,
  ArrowBackIos as ArrowBackIosIcon,
  VisibilityOutlined as VisibilityOutlinedIcon,
  CheckOutlined as CheckOutlinedIcon,
  FileDownloadOutlined as FileDownloadOutlinedIcon,
  Launch as LaunchIcon,
  Edit as EditIcon,
  FmdGood as FmdGoodIcon,
  AccessTime as AccessTimeIcon,
  ImportExport as ImportExportIcon,
  Check as CheckIcon,
  CloudUploadOutlined as CloudUploadOutlinedIcon,
  Autorenew as AutorenewIcon,
  EditOutlined as EditOutlinedIcon,
  DeleteOutlined as DeleteOutlinedIcon,
  Undo as UndoIcon,
  Timeline as TimelineIcon,
  DescriptionOutlined as DescriptionOutlinedIcon,
  PeopleAlt as PeopleAltIcon,
  Tune as TuneIcon,
  FormatBold as FormatBoldIcon,
  FormatItalic as FormatItalicIcon,
  StrikethroughS as StrikethroughSIcon,
  FormatListNumbered as FormatListNumberedIcon,
  Code as CodeIcon,
  Redo as RedoIcon,
  FormatQuote as FormatQuoteIcon,
  AddPhotoAlternateOutlined as ImageAddIcon,
  HorizontalRule as HorizontalRuleIcon,
  VideoFileOutlined as VideoFileOutlinedIcon,
  QuestionAnswer as QuestionAnswerIcon,
  IntegrationInstructions as IntegrationInstructionsIcon,
  QrCode2Outlined as QrCode2OutlinedIcon,
  BarChart as BarChartIcon,
  CalendarTodayOutlined as CalendarTodayOutlinedIcon,
  ChevronRight as ChevronRightIcon,
  ChevronLeft as ChevronLeftIcon,
  RotateLeft as RotateLeftIcon,
  RotateRight as RotateRightIcon,
  Sync as SyncIcon,
  ExpandMore as ExpandMoreIcon,
  CheckBox as CheckBoxIcon,
  CheckBoxOutlineBlank as CheckBoxOutlineBlankIcon,
  UnfoldMore as UnfoldMoreIcon,
  ManageAccountsOutlined as ManageAccountsOutlinedIcon,
  LogoutOutlined as LogoutOutlinedIcon,
  ArrowDropDown as ArrowDropDownIcon,
  AlternateEmail as AlternateEmailIcon,
  BarChartOutlined as BarChartOutlinedIcon,
  MapOutlined as MapOutlinedIcon,
  HistoryOutlined as HistoryOutlinedIcon,
  LockOutlined as LockOutlinedIcon,
  ContentCopy as ContentCopyIcon,
  InfoOutlined as InfoOutlineIcon,
} from '@mui/icons-material';
import LockPng from '@/assets/images/lock.png';
import RedLockPng from '@/assets/images/red-lock.png';
import MapPinRed from '@/assets/images/map-pin-primary.png';
import MapPinGrey from '@/assets/images/map-pin-grey.png';
import { styled, alpha } from '@mui/material/styles';
export default {
  ExitToAppIcon,
  ShareIcon,
  VerifiedIcon,
  LockOpenIcon,
  DescriptionIcon,
  FileDownloadIcon,
  LocationOn,
  AutoAwesome,
  SearchIcon,
  styled,
  alpha,
  CloseIcon,
  PersonIcon,
  LoginIcon,
  KeyboardArrowDownIcon,
  DarkModeIcon,
  LightModeIcon,
  MenuIcon,
  LinkIcon,
  RectangleIcon,
  AccessTimeFilledIcon,
  LockIcon,
  FullscreenIcon,
  GridViewIcon,
  AddIcon,
  FormatAlignCenterIcon,
  RemoveIcon,
  KeyboardDoubleArrowUpIcon,
  KeyboardDoubleArrowDownIcon,
  SettingsSuggestIcon,
  ArrowBackIcon,
  LockPng,
  RedLockPng,
  MapPinRed,
  MapPinGrey,
  TaskIcon,
  SubmissionIcon,
  FeatureIcon,
  BoltIcon,
  WindowIcon,
  ListViewIcon,
  FilterAltIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  DoneIcon,
  ReplayIcon,
  SettingsIcon,
  DriveFolderUploadIcon,
  KeyboardArrowUpIcon,
  InfoIcon,
  MoreVertIcon,
  LocationOnIcon,
  CropFreeIcon,
  LegendToggleIcon,
  DeleteIcon,
  ListAltIcon,
  MapIcon,
  FilterAltOutlinedIcon,
  ArrowForwardIosIcon,
  ArrowBackIosIcon,
  VisibilityOutlinedIcon,
  CheckOutlinedIcon,
  FileDownloadOutlinedIcon,
  LaunchIcon,
  EditIcon,
  FmdGoodIcon,
  AccessTimeIcon,
  ImportExportIcon,
  CheckIcon,
  CloudUploadOutlinedIcon,
  AutorenewIcon,
  EditOutlinedIcon,
  DeleteOutlinedIcon,
  UndoIcon,
  TimelineIcon,
  DescriptionOutlinedIcon,
  PeopleAltIcon,
  TuneIcon,
  FormatBoldIcon,
  FormatItalicIcon,
  StrikethroughSIcon,
  FormatListNumberedIcon,
  CodeIcon,
  RedoIcon,
  FormatQuoteIcon,
  ImageAddIcon,
  HorizontalRuleIcon,
  VideoFileOutlinedIcon,
  QuestionAnswerIcon,
  IntegrationInstructionsIcon,
  QrCode2OutlinedIcon,
  BarChartIcon,
  CalendarTodayOutlinedIcon,
  ChevronRightIcon,
  ChevronLeftIcon,
  RotateLeftIcon,
  RotateRightIcon,
  SyncIcon,
  ExpandMoreIcon,
  CheckBoxIcon,
  CheckBoxOutlineBlankIcon,
  UnfoldMoreIcon,
  ManageAccountsOutlinedIcon,
  LogoutOutlinedIcon,
  ArrowDropDownIcon,
  AlternateEmailIcon,
  BarChartOutlinedIcon,
  MapOutlinedIcon,
  HistoryOutlinedIcon,
  LockOutlinedIcon,
  ContentCopyIcon,
  InfoOutlineIcon,
};
