FROM docker.io/node:20-slim
RUN set -ex \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install \
    -y --no-install-recommends \
          "openssl" \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=code ./package.json ./pnpm-lock.yaml ./
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable && corepack use pnpm@9.15.4
RUN pnpm install
ENTRYPOINT ["pnpm", "run", "dev"]
